
spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/devpaydb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%Thread] %-5level %logger{36} - %msg%n"