
spring:
  application:
    name: user-service
    secret: gdxsfgqaswfqywfuyhjcgxfwyasrdytqwredug246eewg67127t8y1812eetew73w6712671276
    expiration: 86400000

  datasource:
    url: jdbc:mysql://localhost:3306/devpaydb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    in.devpay: DEBUG   # 👈 this enables debug logs for your project packages
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%Thread] %-5level %logger{36} - %msg%n"